<table width="766" border="0" cellspacing="0" cellpadding="0" align="center" height="129" background="images/down.gif">
  <tr align="center" valign="top"> 
    <td><div class="address"><br>
      ADDRESS:<br>
      15, Efimova str, Odessa, Ukraine<br>
      <b>[+380] (67) 11-33-600 viber</b><br>
      tel.: [+380] (67) 553-13-34, [+380] (50) 863-77-69<br>
   </div></td>
  </tr>
</table>
