<div class="photo">

<table border="0" cellspacing="0" cellpadding="0" align="center">
 <tr align="center" valign="middle"> 
  <td><a id="thumb11" href="images/gallery/049_b.jpg" class="highslide" onclick="return hs.expand(this)"><img src="images/gallery/049_p.jpg" alt="<? echo $alttext; ?>" title="<? echo $titletext; ?>" width="150" height="130"></a><div class="highslide-caption">Фото 1-1</div></td>
  <td><a id="thumb12" href="images/gallery/003_b.jpg" class="highslide" onclick="return hs.expand(this)"><img src="images/gallery/003_p.jpg" alt="<? echo $alttext; ?>" title="<? echo $titletext; ?>" width="150" height="130"></a><div class="highslide-caption">Фото 1-2</div></td>
  <td><a id="thumb25" href="images/gallery/051_b.jpg" class="highslide" onclick="return hs.expand(this)"><img src="images/gallery/051_p.jpg" alt="<? echo $alttext; ?>" title="<? echo $titletext; ?>" width="150" height="130"></a><div class="highslide-caption">Фото 2-3</div></td>
 </tr>

 <tr align="center" valign="middle"> 
  <td><a id="thumb33" href="images/gallery/015_b.jpg" class="highslide" onclick="return hs.expand(this)"><img src="images/gallery/015_p.jpg" alt="<? echo $alttext; ?>" title="<? echo $titletext; ?>" width="150" height="130"></a><div class="highslide-caption">Фото 3-1</div></td>
  <td><a id="thumb34" href="images/gallery/017_b.jpg" class="highslide" onclick="return hs.expand(this)"><img src="images/gallery/017_p.jpg" alt="<? echo $alttext; ?>" title="<? echo $titletext; ?>" width="150" height="130"></a><div class="highslide-caption">Фото 3-2</div></td>
  <td><a id="thumb35" href="images/gallery/052_b.jpg" class="highslide" onclick="return hs.expand(this)"><img src="images/gallery/052_p.jpg" alt="<? echo $alttext; ?>" title="<? echo $titletext; ?>" width="150" height="130"></a><div class="highslide-caption">Фото 3-3</div></td>
 </tr>

 <tr align="center" valign="middle"> 
  <td><a id="thumb43" href="images/gallery/044_b.jpg" class="highslide" onclick="return hs.expand(this)"><img src="images/gallery/044_p.jpg" alt="<? echo $alttext; ?>" title="<? echo $titletext; ?>" width="150" height="130"></a><div class="highslide-caption">Фото 4-1</div></td>
  <td><a id="thumb53" href="images/gallery/010_b.jpg" class="highslide" onclick="return hs.expand(this)"><img src="images/gallery/010_p.jpg" alt="<? echo $alttext; ?>" title="<? echo $titletext; ?>" width="150" height="130"></a><div class="highslide-caption">Фото 5-1</div></td>
  <td><a id="thumb63" href="images/gallery/041_b.jpg" class="highslide" onclick="return hs.expand(this)"><img src="images/gallery/041_p.jpg" alt="<? echo $alttext; ?>" title="<? echo $titletext; ?>" width="150" height="130"></a><div class="highslide-caption">Фото 6-1</div></td>
 </tr>

 <tr align="center" valign="middle"> 
  <td><a id="thumb64" href="images/gallery/039_b.jpg" class="highslide" onclick="return hs.expand(this)"><img src="images/gallery/039_p.jpg" alt="<? echo $alttext; ?>" title="<? echo $titletext; ?>" width="150" height="130"></a><div class="highslide-caption">Фото 6-2</div></td>
  <td><a id="thumb65" href="images/gallery/046_b.jpg" class="highslide" onclick="return hs.expand(this)"><img src="images/gallery/046_p.jpg" alt="<? echo $alttext; ?>" title="<? echo $titletext; ?>" width="150" height="130"></a><div class="highslide-caption">Фото 6-3</div></td>
  <td><a id="thumb73" href="images/gallery/053_b.jpg" class="highslide" onclick="return hs.expand(this)"><img src="images/gallery/053_p.jpg" alt="<? echo $alttext; ?>" title="<? echo $titletext; ?>" width="150" height="130"></a><div class="highslide-caption">Фото 7-1</div></td>
 </tr>

 <tr align="center" valign="middle"> 
  <td><a id="thumb84" href="images/gallery/045_b.jpg" class="highslide" onclick="return hs.expand(this)"><img src="images/gallery/045_p.jpg" alt="<? echo $alttext; ?>" title="<? echo $titletext; ?>" width="150" height="130"></a><div class="highslide-caption">Фото 8-2</div></td>
  <td><a id="thumb95" href="images/gallery/057_b.jpg" class="highslide" onclick="return hs.expand(this)"><img src="images/gallery/057_p.jpg" alt="<? echo $alttext; ?>" title="<? echo $titletext; ?>" width="150" height="130"></a><div class="highslide-caption">Фото 9-3</div></td>
  <td><a id="thumbA3" href="images/gallery/056_b.jpg" class="highslide" onclick="return hs.expand(this)"><img src="images/gallery/056_p.jpg" alt="<? echo $alttext; ?>" title="<? echo $titletext; ?>" width="150" height="130"></a><div class="highslide-caption">Фото 10-1</div></td>
 </tr>

 <tr align="center" valign="middle"> 
  <td><a id="thumbB3" href="images/gallery/060_b.jpg" class="highslide" onclick="return hs.expand(this)"><img src="images/gallery/060_p.jpg" alt="<? echo $alttext; ?>" title="<? echo $titletext; ?>" width="150" height="130"></a><div class="highslide-caption">Фото 11-1</div></td>
  <td><a id="thumbB4" href="images/gallery/038_b.jpg" class="highslide" onclick="return hs.expand(this)"><img src="images/gallery/038_p.jpg" alt="<? echo $alttext; ?>" title="<? echo $titletext; ?>" width="150" height="130"></a><div class="highslide-caption">Фото 11-2</div></td>
  <td><a id="thumbB5" href="images/gallery/033_b.jpg" class="highslide" onclick="return hs.expand(this)"><img src="images/gallery/033_p.jpg" alt="<? echo $alttext; ?>" title="<? echo $titletext; ?>" width="150" height="130"></a><div class="highslide-caption">Фото 11-3</div></td>
 </tr>

 <tr align="center" valign="middle"> 
  <td><a id="thumbC1" href="images/gallery/100_b.jpg" class="highslide" onclick="return hs.expand(this)"><img src="images/gallery/100_p.jpg" alt="<? echo $alttext; ?>" title="<? echo $titletext; ?>" width="150" height="130"></a><div class="highslide-caption">Фото 12-1</div></td>
  <td><a id="thumbC2" href="images/gallery/101_b.jpg" class="highslide" onclick="return hs.expand(this)"><img src="images/gallery/101_p.jpg" alt="<? echo $alttext; ?>" title="<? echo $titletext; ?>" width="150" height="130"></a><div class="highslide-caption">Фото 12-2</div></td>
  <td><a id="thumbC3" href="images/gallery/102_b.jpg" class="highslide" onclick="return hs.expand(this)"><img src="images/gallery/102_p.jpg" alt="<? echo $alttext; ?>" title="<? echo $titletext; ?>" width="150" height="130"></a><div class="highslide-caption">Фото 12-3</div></td>
 </tr>                                                                                                                               
                                                                                                                                     
 <tr align="center" valign="middle">                                                                                                 
  <td><a id="thumbD1" href="images/gallery/103_b.jpg" class="highslide" onclick="return hs.expand(this)"><img src="images/gallery/103_p.jpg" alt="<? echo $alttext; ?>" title="<? echo $titletext; ?>" width="150" height="130"></a><div class="highslide-caption">Фото 13-1</div></td>
  <td><a id="thumbD2" href="images/gallery/104_b.jpg" class="highslide" onclick="return hs.expand(this)"><img src="images/gallery/104_p.jpg" alt="<? echo $alttext; ?>" title="<? echo $titletext; ?>" width="150" height="130"></a><div class="highslide-caption">Фото 13-2</div></td>
  <td><a id="thumbD3" href="images/gallery/105_b.jpg" class="highslide" onclick="return hs.expand(this)"><img src="images/gallery/105_p.jpg" alt="<? echo $alttext; ?>" title="<? echo $titletext; ?>" width="150" height="130"></a><div class="highslide-caption">Фото 13-3</div></td>
 </tr>                                                                                                                               
                                                                                                                                     
 <tr align="center" valign="middle">                                                                                                 
  <td><a id="thumbE1" href="images/gallery/106_b.jpg" class="highslide" onclick="return hs.expand(this)"><img src="images/gallery/106_p.jpg" alt="<? echo $alttext; ?>" title="<? echo $titletext; ?>" width="150" height="130"></a><div class="highslide-caption">Фото 14-1</div></td>
  <td><a id="thumbE2" href="images/gallery/107_b.jpg" class="highslide" onclick="return hs.expand(this)"><img src="images/gallery/107_p.jpg" alt="<? echo $alttext; ?>" title="<? echo $titletext; ?>" width="150" height="130"></a><div class="highslide-caption">Фото 14-2</div></td>
  <td><a id="thumbE3" href="images/gallery/108_b.jpg" class="highslide" onclick="return hs.expand(this)"><img src="images/gallery/108_p.jpg" alt="<? echo $alttext; ?>" title="<? echo $titletext; ?>" width="150" height="130"></a><div class="highslide-caption">Фото 14-3</div></td>
 </tr>                                                                                                                               
                                                                                                                                     
 <tr align="center" valign="middle">                                                                                                 
  <td><a id="thumbF1" href="images/gallery/109_b.jpg" class="highslide" onclick="return hs.expand(this)"><img src="images/gallery/109_p.jpg" alt="<? echo $alttext; ?>" title="<? echo $titletext; ?>" width="150" height="130"></a><div class="highslide-caption">Фото 15-1</div></td>
  <td><a id="thumbF2" href="images/gallery/110_b.jpg" class="highslide" onclick="return hs.expand(this)"><img src="images/gallery/110_p.jpg" alt="<? echo $alttext; ?>" title="<? echo $titletext; ?>" width="150" height="130"></a><div class="highslide-caption">Фото 15-2</div></td>
  <td><a id="thumbF3" href="images/gallery/111_b.jpg" class="highslide" onclick="return hs.expand(this)"><img src="images/gallery/111_p.jpg" alt="<? echo $alttext; ?>" title="<? echo $titletext; ?>" width="150" height="130"></a><div class="highslide-caption">Фото 15-3</div></td>
 </tr>                                                                                                                               
                                                                                                                                     
 <tr align="center" valign="middle">                                                                                                 
  <td><a id="thumbG1" href="images/gallery/112_b.jpg" class="highslide" onclick="return hs.expand(this)"><img src="images/gallery/112_p.jpg" alt="<? echo $alttext; ?>" title="<? echo $titletext; ?>" width="150" height="130"></a><div class="highslide-caption">Фото 16-1</div></td>
  <td><a id="thumbG2" href="images/gallery/113_b.jpg" class="highslide" onclick="return hs.expand(this)"><img src="images/gallery/113_p.jpg" alt="<? echo $alttext; ?>" title="<? echo $titletext; ?>" width="150" height="130"></a><div class="highslide-caption">Фото 16-2</div></td>
  <td><a id="thumbG3" href="images/gallery/114_b.jpg" class="highslide" onclick="return hs.expand(this)"><img src="images/gallery/114_p.jpg" alt="<? echo $alttext; ?>" title="<? echo $titletext; ?>" width="150" height="130"></a><div class="highslide-caption">Фото 16-3</div></td>
 </tr>                                                                                                                               
                                                                                                                                     
 <tr align="center" valign="middle">                                                                                                 
  <td><a id="thumbH1" href="images/gallery/115_b.jpg" class="highslide" onclick="return hs.expand(this)"><img src="images/gallery/115_p.jpg" alt="<? echo $alttext; ?>" title="<? echo $titletext; ?>" width="150" height="130"></a><div class="highslide-caption">Фото 17-1</div></td>
  <td><a id="thumbH2" href="images/gallery/116_b.jpg" class="highslide" onclick="return hs.expand(this)"><img src="images/gallery/116_p.jpg" alt="<? echo $alttext; ?>" title="<? echo $titletext; ?>" width="150" height="130"></a><div class="highslide-caption">Фото 17-2</div></td>
  <td><a id="thumbH3" href="images/gallery/117_b.jpg" class="highslide" onclick="return hs.expand(this)"><img src="images/gallery/117_p.jpg" alt="<? echo $alttext; ?>" title="<? echo $titletext; ?>" width="150" height="130"></a><div class="highslide-caption">Фото 17-3</div></td>
 </tr>                                                                                                                               
                                                                                                                                     
 <tr align="center" valign="middle">                                                                                                 
  <td><a id="thumbI1" href="images/gallery/118_b.jpg" class="highslide" onclick="return hs.expand(this)"><img src="images/gallery/118_p.jpg" alt="<? echo $alttext; ?>" title="<? echo $titletext; ?>" width="150" height="130"></a><div class="highslide-caption">Фото 18-1</div></td>
  <td><a id="thumbI2" href="images/gallery/119_b.jpg" class="highslide" onclick="return hs.expand(this)"><img src="images/gallery/119_p.jpg" alt="<? echo $alttext; ?>" title="<? echo $titletext; ?>" width="150" height="130"></a><div class="highslide-caption">Фото 18-2</div></td>
  <td>&nbsp;</td>
 </tr>
 </table>
</div>
