    <div style="padding-left:3%; padding-right:3%">
      <table width="100%" border="0" cellspacing="0" cellpadding="0" height="30" align="center">
        <tr align="center" valign="middle"> 
          
          <td>
            <div class="menu">
<a href="index_ua.php" onMouseOut="MM_swapImgRestore()" onMouseOver="MM_swapImage('Image1','','images/about_over.gif',1)">
<img name="Image1" border="0" src="images/about_out.gif" width="67" height="30" alt="Про баню"></a> 
            </div>
          </td>

          <td>
            <div class="menu">
<a href="service_ua.php" onMouseOut="MM_swapImgRestore()" onMouseOver="MM_swapImage('Image2','','images/service_over.gif',1)">
<img name="Image2" border="0" src="images/service_out.gif" width="60" height="30" alt="Цiни"></a> 
            </div>
          </td>

          <td>
            <div class="menu">
<a href="gallery_ua.php" onMouseOut="MM_swapImgRestore()" onMouseOver="MM_swapImage('Image3','','images/gallery_over.gif',1)">
<img name="Image3" border="0" src="images/gallery_out.gif" width="123" height="30" alt="Фотогалерея"></a> 
            </div>
          </td>

          <td>
            <div class="menu">
<a href="restaurant_ua.php" onMouseOut="MM_swapImgRestore()" onMouseOver="MM_swapImage('Image4','','images/restaurant_over.gif',1)">
<img name="Image4" border="0" src="images/restaurant_out.gif" width="110" height="30" alt="Ресторан"></a> 
            </div>
          </td>

            <td>
            <div class="menu">
<a href="actions_ua.php" onMouseOut="MM_swapImgRestore()" onMouseOver="MM_swapImage('Image7','','images/action_over.gif',1)">
<img name="Image7" border="0" src="images/action_out.gif" width="67" height="30" alt="Акцiї"></a> 
            </div>
          </td>


          <td>
            <div class="menu">
<a href="contacts_ua.php" onMouseOut="MM_swapImgRestore()" onMouseOver="MM_swapImage('Image9','','images/contacts_over.gif',1)">
<img name="Image9" border="0" src="images/contacts_out.gif" width="110" height="30" alt="Контакти"></a> 
            </div>
          </td>

        </tr>
      </table>
    </div>
    <br>
