<? 
$TitleGlobal    = 'Баня &laquo;ЛЕГКИЙ ПАР&raquo;, г. Одесса, ул. Ефимова, 15.';
$TitleGlobal_Ua = 'Баня &laquo;ЛЕГКИЙ ПАР&raquo;, м. Одеса, вул. Єфiмова, 15.';
$TitleGlobal_En = 'Banja &laquo;LEHKIJ PAR&raquo;, Odessa, Efimova str, 15.';
?>
<meta HTTP-EQUIV="content-type" content="text/html; charset=windows-1251">
<meta name="description" content="Клуб нацiональної культури здоров'я Легкий пар. Україна, м. Одеса, вул. Єфiмова, 15">
<meta name="page-topic" content="Клуб нацiональної культури здоров'я Легкий пар. ruspar.od.uа">
<meta name="Copyright" content="Клуб нацiональної культури здоров'я Легкий пар">
<meta name="abstract" content="Клуб нацiональної культури здоров'я Легкий пар. ruspar.od.uа">
<meta name="keywords" content="легкий пар, баня, парна, оздоровчий масаж, банний клуб, парилка, банний квас, чай, банний комплекс, бджолиний мед, одеса, єфiмова, банька, масаж спини, масаж нiг, загальний оздоровчий масаж, банний вiник">
<meta name="audience" content="all">
<meta name="revisit" content="7 days">
<meta name="robots" content="index, all">
<meta name="author" content="http://www.ruspar.od.ua">
<meta HTTP-EQUIV="Reply-to" content="info@ruspar.od.ua">
<link href="http://www.ruspar.od.ua/ruspar.css" type="text/css" rel="stylesheet">
<link rel="icon" href="/favicon.ico" type="image/x-icon">
<link rel="shortcut icon" href="/favicon.ico" type="image/x-icon">
<script language="JavaScript" src="include/rel_menu.js"></script>

<!-- Global site tag (gtag.js) - Google Analytics -->
<script async src="https://www.googletagmanager.com/gtag/js?id=UA-70849699-2">
</script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'UA-70849699-2');
</script>
