<center><h2>Индивидуально каждый клиент может воспользоваться следующими услугами:</h2></center>
<br>

<table width="100%" border="0" cellspacing="0" cellpadding="4">
 <tr>
  <td align=left><li><b>Веничное парение (10-12 мин)</b> на банном полке с растиранием тела рукавицей из натуральных волокон или березовым веником</td>
  <td align=right><? print str_pad ('', 15, ".", STR_PAD_BOTH);?></td>
  <td align=right><b>455&nbsp;грн</b></td>
 </tr>

 <tr>
  <td align=left><li><b>"По-Царски" (16-18 мин)</b> индивидуальная программа для клиента</td>
  <td align=right><? print str_pad ('', 15, ".", STR_PAD_BOTH);?></td>
  <td align=right><b>700&nbsp;грн</b></td>
 </tr>

 <tr>
  <td align=left><li><b>"Лед и пламя" (12-14 мин)</b> веничное парение на банном полке с растиранием тела льдом</td>
  <td align=right><? print str_pad ('', 15, ".", STR_PAD_BOTH);?></td>
  <td align=right><b>490&nbsp;грн</b></td>
 </tr>

 <tr>
  <td align=left><li><b>"Дуплет" (19-22 мин)</b> двойное веничное парение на банном полке с купанием в холодном бассейне</td>
  <td align=right><? print str_pad ('', 15, ".", STR_PAD_BOTH);?></td>
  <td align=right><b>775&nbsp;грн</b></td>
 </tr>

 <tr>
  <td align=left><li><b>"Сибирка" (12-14 мин)</b> веничное парение на банном полке с обливанием тела холодной водой</td>
  <td align=right><? print str_pad ('', 15, ".", STR_PAD_BOTH);?></td>
  <td align=right><b>490&nbsp;грн</b></td>
 </tr>

 <tr>
  <td align=left><li><b>Мыльно-березовое очищение (13-15 мин)</b> тела с применением березового веника или рукавицы из натуральных волокон с последующим прогреванием на банном полке при помощи простыни</td>
  <td align=right><? print str_pad ('', 15, ".", STR_PAD_BOTH);?></td>
  <td align=right><b>475&nbsp;грн</b></td>
 </tr>                

 <tr>
  <td align=left><li><b>Скраб "Цитрусовый": (15-18 мин)</b><br>
  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;- растирание тела смесью соли и цитрусов (лимон, апельсин, грейпфрут)<br>
  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;- прогрев на банном полке<br>
  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;- растирание тела различными сортами меда
  </td>
  <td align=right><? print str_pad ('', 15, ".", STR_PAD_BOTH);?></td>
  <td align=right><b>495&nbsp;грн</b></td>
 </tr>

 <tr>
  <td align=left><li><b>Скраб "Имбирный": (15-18 мин)</b><br>
  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;- растирание тела смесью соли и имбиря<br>
  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;- прогрев на банном полке<br>
  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;- растирание тела различными сортами меда
  </td>
  <td align=right><? print str_pad ('', 15, ".", STR_PAD_BOTH);?></td>
  <td align=right><b>495&nbsp;грн</b></td>
 </tr>

 <tr>
  <td align=left><li><b>Скраб на основе виноградной косточки: (15-18 мин)</b><br>
  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;- растирание тела смесью соли и виноградной косточки<br>
  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;- прогрев на банном полке<br>
  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;- растирание тела различными сортами меда
  </td>
  <td align=right><? print str_pad ('', 15, ".", STR_PAD_BOTH);?></td>
  <td align=right><b>495&nbsp;грн</b></td>
 </tr>

 <tr>
  <td align=left><li><b>Скраб на основе хрена: (15-18 мин)</b><br>
  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;- растирание тела смесью соли и хрена<br>
  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;- прогрев на банном полке<br>
  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;- растирание тела различными сортами меда
  </td>
  <td align=right><? print str_pad ('', 15, ".", STR_PAD_BOTH);?></td>
  <td align=right><b>495&nbsp;грн</b></td>
 </tr>

 <tr>
  <td align=left><li><b>Скрабирование (10-12 мин)</b> тела и головы смесью соли, горчичного порошка, различных сортов меда и светлых сортов пива по старославянскому методу</td>
  <td align=right><? print str_pad ('', 15, ".", STR_PAD_BOTH);?></td>
  <td align=right><b>455&nbsp;грн</b></td>
 </tr>

 <tr>
  <td align=left><li><b>Комплекс горчично-медовый: (15-18 мин)</b><br>
  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;- растирание тела смесью соли и горчичного порошка<br>
  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;- прогрев на банном полке<br>
  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;- растирание тела различными сортами меда
  </td>
  <td align=right><? print str_pad ('', 15, ".", STR_PAD_BOTH);?></td>
  <td align=right><b>495&nbsp;грн</b></td>
 </tr>

 <tr>
  <td align=left><li><b>Комплекс кофейно-медовый: (15-18 мин)</b><br>
  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;- растирание тела смесью соли и натурального кофе<br>
  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;- прогрев на банном полке<br>
  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;- растирание тела различными сортами меда
  </td>
  <td align=right><? print str_pad ('', 15, ".", STR_PAD_BOTH);?></td>
  <td align=right><b>495&nbsp;грн</b></td>
 </tr>

 <tr>
  <td align=left><li><b>Комплекс березово-медовый: (19-22 мин)</b><br>
  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;- мыльно-березовое очищение тела<br>
  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;- прогрев на банном полке с применением простыни<br>
  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;- растирание тела различными сортами меда
  </td>
  <td align=right><? print str_pad ('', 15, ".", STR_PAD_BOTH);?></td>
  <td align=right><b>560&nbsp;грн</b></td>
 </tr>

 <tr>
  <td align=left><li><b>Купель</b> - успокаивающая и расслабляющая ванна из настоя целебных трав в бочке из натурального дуба. Снимает мышечное напряжение, восстанавливает силы</td>
  <td align=right><? print str_pad ('', 15, ".", STR_PAD_BOTH);?></td>
  <td align=right><b>800&nbsp;грн</b></td>
 </tr>

 <tr>
  <td align=left><li>Горячий веничный прогрев на банном полке 3-4 минуты</td>
  <td align=right><? print str_pad ('', 15, ".", STR_PAD_BOTH);?></td>
  <td align=right><b>155&nbsp;грн</b></td>
 </tr>
 
 <tr>
  <td align=left><li>Успокаивающее оздоровительное прогревание ног в ящике с морской солью</td>
  <td align=right><? print str_pad ('', 15, ".", STR_PAD_BOTH);?></td>
  <td align=right><b>155&nbsp;грн</b></td>
 </tr>

 <tr>
  <td align=left><li>Банные махровая и хлопчатобумажная простыни (комплект)</td>
  <td align=right><? print str_pad ('', 15, ".", STR_PAD_BOTH);?></td>
  <td align=right><b>150&nbsp;грн</b></td>
 </tr>

 <tr>
  <td align=left><li>Банный халат махровый</td>
  <td align=right><? print str_pad ('', 15, ".", STR_PAD_BOTH);?></td>
  <td align=right><b>170&nbsp;грн</b></td>
 </tr>

 <tr>
  <td align=left><li>Веник банный в ассортименте (дубовый, березовый, канадский дуб)</td>
  <td align=right><? print str_pad ('', 15, ".", STR_PAD_BOTH);?></td>
  <td align=right><b>135&nbsp;грн</b></td>
 </tr>
</table>
